# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-29 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ['-created_on'], 'verbose_name': 'My Tutorial', 'verbose_name_plural': 'Tutorials'},
        ),
        migrations.AddField(
            model_name='tutorial',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
