# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-30 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20201029_1853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='Projects',
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-pub_date'], 'verbose_name': 'My Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
