# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-30 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_auto_20201030_0431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Tutorials',
        ),
        migrations.AlterModelOptions(
            name='tutorials',
            options={'ordering': ['-pub_date'], 'verbose_name': 'My Tutorial', 'verbose_name_plural': 'Tutorials'},
        ),
    ]
