# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-30 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20201030_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='description',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
